baseURL = 'https://trivikramat.github.io'
languageCode = 'en-us'
title = 'My Photography and Travel Blog'
theme = "hugo-theme-stack"
favicon        = "img/avatar.jpg"
mainSections   = ["post"]
rssFullContent = true
timeout = "600s"

[params]
  [params.sidebar]
    subtitle = "A dream you dream alone is only a dream. A dream you dream together is reality"
    avatar   = "img/avatar.jpg"

  [params.imageProcessing]
    autoOrient = true

  [params.widgets]
    page     = [{ type = "toc" }]

  [params.comments]
    enabled  = true
    provider = "giscus"

  [params.comments.giscus]
    repo = "TrivikramAT/trivikramat.github.io"
    repo_id = "R_kgDOLDWvPQ"
    category = "Announcements"
    category_id = "DIC_kwDOLDWvPc4C4XXG"
    mapping = "pathname"
    strict = 0
    reactionsEnabled = 1
    emitMetadata = 0
    inputPosition = "bottom"
    lang = "en"
    theme = "preferred_color_scheme"

[[menu.social]]
  identifier = "github"
  name       = "GitHub"
  url        = "https://github.com/TrivikramAT"

  [menu.social.params]
      icon = "brand-github"

[[menu.social]]
  identifier = "email"
  name       = "Email"
  url        = "mailto:nosynarwhal@proton.me"

  [menu.social.params]
      icon = "mail"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true

        [markup.goldmark.extensions.passthrough.delimiters]
          block  = [["\\[", "\\]"], ["$$", "$$"]]
          inline = [["\\(", "\\)"]]

[tableOfContents]
  endLevel   = 4
  ordered    = true
  startLevel = 2

[highlight]
  noClasses          = false
  codeFences         = true
  guessSyntax        = true
  lineNoStart        = 1
  lineNos            = true
  lineNumbersInTable = true
  tabWidth           = 4