baseURL = 'https://trivikramat.github.io'
languageCode = 'en-us'
title = 'My Photography and Travel Blog'
theme = "github-style"

[params]
  author = "Trivikram"
  description = "A dream you dream alone is only a dream. A dream you dream together is reality"
  keywords = "blog, google analytics"
  lastmod = true
  favicon = "/images/github-mark.png"
  avatar = "/images/avatar.jpg"
  headerIcon = "/images/github-mark-white.png"
  location = "USA"
  userStatusEmoji = "😀"
  custom_css = ["custom.css"]