baseURL = 'https://trivikramat.github.io'
languageCode = 'en-us'
title = 'My Photography and Travel Blog'
theme = "hugo-theme-stack"
favicon        = "img/avatar.jpg"
mainSections   = ["post"]
rssFullContent = true

[params]
  [params.sidebar]
    subtitle = "A dream you dream alone is only a dream. A dream you dream together is reality"
    avatar   = "img/avatar.jpg"

  [params.imageProcessing]
    autoOrient = true

  [params.widgets]
    page     = [{ type = "toc" }]

[[menu.social]]
  identifier = "github"
  name       = "GitHub"
  url        = "https://github.com/TrivikramAT"

  [menu.social.params]
      icon = "brand-github"

[[menu.social]]
  identifier = "email"
  name       = "Email"
  url        = "mailto:nosynarwhal@proton.me"

  [menu.social.params]
      icon = "mail"

[goldmark]
  [goldmark.extensions]
    [goldmark.extensions.passthrough]
      enable = true

      [goldmark.extensions.passthrough.delimiters]
        block  = [["\\[", "\\]"], ["$$", "$$"]]
        inline = [["\\(", "\\)"]]

  [goldmark.renderer]
    ## Set to true if you have HTML content inside Markdown
    unsafe = true

[tableOfContents]
  endLevel   = 4
  ordered    = true
  startLevel = 2

[highlight]
  noClasses          = false
  codeFences         = true
  guessSyntax        = true
  lineNoStart        = 1
  lineNos            = true
  lineNumbersInTable = true
  tabWidth           = 4

[comments]
  enabled  = true
  provider = "giscus"

  [comments.giscus]
    repo = "TrivikramAT/trivikramat.github.io"
    repoId = "R_kgDOLDWvPQ"
    category = "Announcements"
    categoryId = "DIC_kwDOLDWvPc4C4XXG"
    mapping = "pathname"
    strict = 0
    reactionsEnabled = 1
    emitMetadata = 0
    inputPosition = "bottom"
    lang = "en"
    lightTheme       = "light"
    darkTheme        = "dark_dimmed"